from crewai import Task
from crewai import Agent

def create_research_task(agent: Agent, topic: str) -> Task:
    return Task(
        description=f"""
        Research the following topic thoroughly: *{topic}**
        
        Your research should include:
        1. Key concepts and definitions
        2. Current trends and recent developments
        3. Important statistics or data points
        4. Major players or stakeholders involved
        5. Challanges and opportubities
        6. Future outlook
        
        Use the web search tool multiple times with different search queries
        to gther comprehensive information. Aim for at least 3-5 searches.
        """,
        expected_output="""
        A comprehensive research summary containing:
        - Key findings organized by category
        - Important facts and statistics with sources
        - Current trends and developments
        - At least 500 words of detailed research notes
        """,
        agent=agent
    )

def create_writing_task(agent: Agent, topic: str) -> Task:
    return Task(
        description=f"""
        Based on the research provided, write a comprehensive, well-structured report on: **{topic}**
        
        The report should include:
        1. Executive Summary (2-3 paragraphs)
        2. Introduction
        3. Main findings (organized in clear sections)
        4. Key Statistics & Data
        5. Challenges & Opportunities
        6. Future Outlook
        8. Comclusion
        
        Write in a professional but engagng tone. Use clear headings and subheadings.
        The report should be at least 800-1000 words.
        """,
        expected_output="""
        A well-strucured, professional report in markdown format with:
        - Clear sections and headings
        - Engaging introduction and conclusion
        - Well-oraganized main content
        - At least 800 words
        """,
        agent=agent
    )

def create_critic_task(agent: Agent, topic: str) -> Task:
    return Task(
        description=f"""
        Review the written report on **{topic}** critically.
        
        Check for:
        1. Ethical accuracy - are all claims supported?
        2. Completeness - are they any important aspects missing?
        3. Logical flow - does the report flow logically?
        4. Clarity - is the language clear and accessible?
        5. Grammer and style issues
        6. Any unsupported or exaggerated claims
        
        Provide specific feedback and an improved version of the report
        with your correctenss applied.
        """,
        expected_output="""
        A reviewed and imroved version of the report with:
        - Corrections applied directly
        - Brief note on what was changed and why
        - Final polished content ready for formatting
        """,
        agent=agent
    )

def create_formatting_task(agent: Agent, topic: str) -> Task:
    return Task(
        description=f"""
        Take the reviewed report on **{topic}** and format it into a
        clean, professional final markdown document.
        
        The final document should have:
        1. A professional title
        2. Table of contents
        3. Well-formatted sections with proper markdown headings (##, ###)
        4. Key takeways section at the end
        5. A "Generated by Multi-Agent AI System" footer
        
        Make it visually clean and easy to read.""",
        expected_output="""
        A beautiful formatted final markdown report with:
        - Professional title and table of contents
        - Properly structured sections
        - Key takeways
        - Footer
        - Ready to be converted to PDF or published
        """,
        agent=agent
    )